Repository projeto-de-algoritmos/Grafos2_LootMaze, pull requests merged in 2023-05, with the labels that each got.

#1 Add basic grid rendering
  src/game/grid/__init__.py
  src/game/grid/grid.py
  src/game/main.py
  src/game/path_algorithm/DFS.py
  src/game/path_algorithm/__init__.py
  src/game/path_algorithm/a_star.py
  src/game/path_algorithm/dijkstra.py
  src/game/player/__init__.py
  src/game/player/player.py
Labels: enhancement

#2 Add map generation by reading png file
  src/assets/maps/map.png
  src/config/__init__.py
  src/game/grid/grid.py
  src/game/main.py
Labels: enhancement

#3 Add sprites and isometric visualization of the maze
  src/assets/sprites/ground_tile.png
  src/assets/sprites/lava_tile.png
  src/assets/sprites/wall_tile.png
  src/config/__init__.py
  src/game/grid/grid.py
Labels: enhancement

#4 Adiciona logica do jogador e da escolha de objetivo
  src/game/grid/grid.py
  src/game/main.py
  src/game/path_algorithm/DFS.py
  src/game/path_algorithm/a_star.py
  src/game/path_algorithm/dijkstra.py
  src/game/player/player.py
Labels: enhancement

#5 Add missing goal property on grid class
  src/game/grid/grid.py
  src/game/main.py
Labels: bug

#6 Add pixel art sprites
  src/assets/maps/map_2.png
  src/assets/maps/map_3.png
  src/assets/sprites/door_tile.png
  src/assets/sprites/lootbox.png
  src/assets/sprites/mage.png
  src/assets/sprites/spawn_tile.png
  src/assets/sprites/title.png
Labels: enhancement

#7 Refactor grid and player logic
  src/game/grid/grid.py
  src/game/main.py
  src/game/path_algorithm/DFS.py
  src/game/path_algorithm/a_star.py
  src/game/path_algorithm/dijkstra.py
  src/game/player/player.py
Labels: bug, enhancement

#9 Add hud buttons and background
  src/assets/sprites/button.png
  src/game/game_scene/__init__.py
  src/game/main.py
  src/game/menu/__init__.py
Labels: enhancement
